#!/bin/sh
RCONFIG="/c/Progra~1/R/R-3.4.1/bin/x64/R CMD config"
CXX11="`$RCONFIG CXX11`"
CXX11STD="`$RCONFIG CXX11STD`"
export CXX="$CXX11 $CXX11STD -DCURL_STATICLIB -DLIBXML_STATIC"
export CXXCPP="`$RCONFIG CXXCPP`"
export CXXFLAGS="`$RCONFIG CXXFLAGS`"
export CC="`$RCONFIG CC` -DCURL_STATICLIB -DLIBXML_STATIC"
export CPP="`$RCONFIG CPP`"
export CFLAGS="`$RCONFIG CFLAGS`"

# Link against mingw64 libs
export CPPFLAGS="-I/mingw64/include -DCURL_STATICLIB -DLIBXML_STATIC -DGLIB_STATIC_COMPILATION -DGRAPHITE2_STATIC -DOPJ_STATIC"
export LDFLAGS="-L/mingw64/lib"
export LIBS="-L/mingw64/lib"

# To use 'ar' and stuff from Rtools as well
#RBINPATH=`dirname $CC`
#RBINPATH=`cygpath $RBINPATH`
#export PATH="$RBINPATH:$PATH"
